### ISSUE TITLE
Error when loading bpipe.q

### ISSUE THREAD

**Issue by xinbow-polymer** [KxSystems/cookbook#16]
hi, when trying to load `bpipe.q`, it's complaining `.lib.Require ``config``util``process`.
Could you please provide the location of the scripts which include the missing modules?

**Comment by rianoc-kx** [comment]
They are not available publicly by the user who submitted the code. They noted:

> The main difference is basically more error-checking (getting the error string from the BB API)
I attach the Makefile and some code for wrapping the C code up (although this wont be usable as is as it relies on some other – mostly -  trivial internal libraries)

See in full here: https://github.com/KxSystems/cookbook/commit/5d76ac43bcd81e7f83f65bd44ef970a630bb00f3

**Comment by rianoc-kx** [comment]
If you can compile the `.so` and put it in `bloomberg/lib/bpipe` then if you load this code (possibly with some tweaks needed) first it will then allow `bpipe.q` to load after:

```q
setenv[`KDBROOT;first system"pwd"]
.lib.Require:(::)
.config.Require:(::)
.util.Exists:not ~[()] key @
.util.ensureSym:{if[not 11h~type x;'`NotSyms]}
.log.Error:-2
.config.Require:(::)
.cfg.bpipe.clibFunctions:("SJ*";enlist "|") 0:`:clibFunctions.table
.cfg.bpipe.clibFunctions:update `$"," vs/:argNames from `functionName`numberOfArgs`argNames xcol .cfg.bpipe.clibFunctions
.process.loadFunctionFromLib:{[s;ns;fn;na] .Q.dd[`;ns,fn] set s 2:(fn;na)}
```

```
\l bpipe.q
```

**Comment by rianoc-kx** [comment]
> Thanks for the response and this fixed the origin problem. But loading the bpipe.q still failing because the compiled bpipe.so file couldn't link to libblpapi3_64.so even though the linker is saying attempt to open /opt/blpapi_cpp_3.24.9.1/Linux/libblpapi3_64.so succeeded.
> Am I using an unsupported version of blpapi or any other potential configure issue?


As the library is user submitted and 5 years old I can't offer much wisdom on deeper issues found during attempts at using it.
To support a newer version of the API it would likely need some updates.

Using the Python API in combination with [PyKX](https://code.kx.com/pykx/2.5/index.html) may be a faster integration path.
https://www.bloomberg.com/professional/support/api-library/
