### ISSUE TITLE
Skipping records while reading large CSVs

### ISSUE THREAD

**Issue by 21sumitkhanna** [KxSystems/cookbook#5]
When reading second+ chunks from same file the the script is treating data record as header and thus skips a record.

**shouldn't this portion :**

_// check if we have already read some data from this file
 // if this is the first time we've seen it, then the first row
 // contains the header information, so we want to load it accounting for that
 // in both cases we want to return a table with the same column names
 data:$[filename in filesread; 
  	 [flip columnames!("PSFI S";enlist",")0:rawdata;
          filesread,::filename];
 	  columnnames xcol ("PSFI S";enlist",")0:rawdata];_

**be:**

_// check if we have already read some data from this file
 // if this is the first time we've seen it, then the first row
 // contains the header information, so we want to load it accounting for that
 // in both cases we want to return a table with the same column names
 data:$[filename in filesread; 
  	 [flip columnnames!("PSFI S";enlist",")0:rawdata];
 	  [filesread,::filename;
           columnnames xcol ("PSFI S";enlist",")0:rawdata]];_

**Comment by sv** [comment]
Please submit PR with an example against the file you found this issue

**Comment by ghost** [comment]
Issue left open too long.
