### ISSUE TITLE
'length error in the tickerplant

### ISSUE THREAD

**Issue by eliquinox** [KxSystems/cookbook#6]
Hey all,

When I start up the tick.q with sym.q and feed.q with files provided as follows:
```
q tick.q sym -p 5010
q feed.q
```
The tickerplant process prints `'length` error on every update, which occurs when incorrect number of elements is passed: https://code.kx.com/wiki/Errors

I suspect that this happens when the feed process calls `.u.upd` 

Are there any suggestions as to how to remove this problem?

**Comment by sv** [comment]
Cannot reproduce your issue. Could you provide step by step reproduction with a fresh checkout of the repository?

**Comment by ghost** [comment]
Issue left open too long.
