### ISSUE TITLE
Generating tzinfo is flawed for historic offset changes

### ISSUE THREAD

**Issue by erichards97** [KxSystems/cookbook#9]
The Java code here: https://code.kx.com/q/kb/timezones/ is flawed when it comes to historical offset changes.

The code uses `TimeZone.getTimeZone("...").getRawOffset()`, which as the JavaDoc states, only works for 'now':
![image](https://github.com/KxSystems/cookbook/assets/30480510/75ca45cb-ac79-41d2-930d-270edf2bd2c9)

This issue is seen when generating tzinfo for _Europe/Istanbul_ - it returns +3h perpetually even though this should only be the case in more recent years (Oct 2018+); in older years it should still alternate between +2h and +3h.

![image](https://github.com/KxSystems/cookbook/assets/30480510/b8f7b6a0-b0f1-4d52-9846-dcb4c2c4eeeb)

Using `ZonedDateTime.of(year, month, day, hour, min, sec, nano, ZoneId.of("...")).getOffset()` accurately returns historic offsets. It is not clear to me why storing DST as a separate offset was required in the first place.

```
        System.out.println("Europe/Istanbul 2000.01.01 offset:");
        ZonedDateTime zdtOne = ZonedDateTime.of(2000,1,1,9,15,0,0, ZoneId.of("Europe/Istanbul"));
        System.out.println(zdtOne.getOffset()); // +02:00
        System.out.println("Europe/Istanbul 2000.06.01 offset:");
        ZonedDateTime zdtTwo = ZonedDateTime.of(2000,6,1,9,15,0,0, ZoneId.of("Europe/Istanbul"));
        System.out.println(zdtTwo.getOffset()); // +03:00
```

**Comment by erichards97** [comment]
Please see https://github.com/KxSystems/cookbook/pull/10 for a candidate solution

**Comment by sshanks-kx** [comment]
Thanks. Currently checking info

Referencing https://www.timeanddate.com/time/zone/turkey/istanbul has
```
1973	Sun, 3 Jun, 01:00	EET → EEST	+1 hour (DST start)	UTC+3h
 	Sun, 4 Nov, 03:00	EEST → EET	-1 hour (DST end)	UTC+2h
1974	Sun, 31 Mar, 02:00	EET → EEST	+1 hour (DST start)	UTC+3h
 	Sun, 3 Nov, 05:00	EEST → EET	-1 hour (DST end)	UTC+2h
```
Current (wrong)
```
Europe/Istanbul,1973.06.02D23:00:00.000,10800,0
Europe/Istanbul,1973.11.03D23:00:00.000,10800,0
Europe/Istanbul,1974.03.31D00:00:00.000,10800,0
Europe/Istanbul,1974.11.02D23:00:00.000,10800,0
```
Proposed (looks better)
```
Europe/Istanbul,1973.06.02D23:00:00.000,10800
Europe/Istanbul,1973.11.03D23:00:00.000,7200
Europe/Istanbul,1974.03.31D00:00:00.000,10800
Europe/Istanbul,1974.11.02D23:00:00.000,7200
```

**Comment by sshanks-kx** [comment]
Pull request in to update doc on https://github.com/KxSystems/docs/pull/124

**Comment by JosieMD** [comment]
Ed, thanks for your input to the q/kdb documentation set and also for your patience while we assigned one of our technical team to investigate.
